---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bds
  labels:
    app: bds
spec:
  replicas: 1
  template:
    metadata:
      name: bds
      labels:
        app: bds
    spec:
      containers:
        
        - name: cloudcmd
          image: coderaiser/cloudcmd
          volumeMounts:
            - mountPath: /data
              name: data
          args:
            - --root
            - /data
            - --port
            - "8000"
            - --auth
            - --username 
            - bds
            - --password
            - andrewstech  
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bds
  selector:
    matchLabels:
      app: bds

---
apiVersion: v1
kind: Service
metadata:
  name: bds-cloudcmd
spec:
  selector:
    app: bds
  ports:
    - port: 8000
      protocol: TCP
      name: cloudcmd  
  type: LoadBalancer
